### ISSUE TITLE
onCloseCodeCallback not getting called when close code is absent

### ISSUE THREAD

**Issue by zmeyc** [vapor/websocket-kit#15]
As per https://tools.ietf.org/html/rfc6455 section 5.5.1 closing code may be absent. In particular, Safari/Chrome/Firefox seem not to send it thus onCloseCodeCallback is not getting called at all:
```
        if let closeCode = data.readInteger(as: UInt16.self)
            .map(Int.init)
            .flatMap(WebSocketErrorCode.init(codeNumber:))
        {
            webSocket.onCloseCodeCallback(closeCode)
        }
```
It would be nice to have that callback called even if there's no code so app could stop sending data to client at this point without waiting for `onClose {}`.

Also there's `reason` field which the lib does not currently fetch which also belongs to that callback imo.

I propose renaming it to `onClosingHandshakeBegin` or `onCloseFrameReceived` with params `(code: WebSocketErrorCode?, reason: String?)`. If it sounds good, I can make a PR.

**Comment by albertaleksieiev** [comment]
@zmeyc I believe that `onClose.always` will be helpfull :)
```
webSocket.onClose.always {
// handle close            
}
```

**Comment by zmeyc** [comment]
@albertaleksieiev Ideally the app should stop sending data to client on the start of closing handshake (when close frame is received) without waiting for onClose and it's currently undetectable in some cases as the callback is not getting called.
