### ISSUE TITLE
WebSocket.send guaranty delivery

### ISSUE THREAD

**Issue by guarland** [vapor/websocket-kit#32]
Is there any way to guarantee delivery via WebSocket.send, or catch an error when not delivering,

**Comment by tanner0101** [comment]
`send` accepts a promise: https://github.com/vapor/websocket/blob/master/Sources/WebSocket/WebSocket.swift#L182

That will succeed (or fail) when the channel write is done: https://github.com/vapor/websocket/blob/master/Sources/WebSocket/WebSocket.swift#L290

**Comment by saroar** [comment]
@tanner0101 both link does not work

**Comment by grundoon** [comment]
@saroar Many things have changed in `master` since those links were posted. At the moment they look to be at:

https://github.com/vapor/websocket-kit/blob/master/Sources/WebSocketKit/WebSocket.swift#L60-L65

https://github.com/vapor/websocket-kit/blob/master/Sources/WebSocketKit/WebSocket.swift#L76
