### ISSUE TITLE
How send binary data?

### ISSUE THREAD

**Issue by malcommac** [vapor/websocket-kit#64]
Hi,
I've tried to modify the example in tests in order to send a small image as NSData.

This is the change on server side:

```swift
return WebSocket.server(on: channel) { ws in
  let data = UIImage(named: "test")!.pngData()!
  let byteArray = [UInt8](data)
  ws.send(raw: byteArray, opcode: .binary)
}
````

And this insie the portion of the client

```swift
WebSocket.connect(to: "ws://localhost:\(port)", on: self.elg) { ws in
  ws.onBinary { (socket, bytes) in
    let data = bytes.getData(at: 0, length: bytes.capacity)
    let imageFromData = UIImage(data: data!)
    ws.close(promise: nil)
}
}.cascadeFailure(to: promise)
```

However message is never received anything inside `ws.onBinary`. Where am I wrong?

**Comment by tanner0101** [comment]
Hi @malcommac. Which version of this package are you using?

**Comment by malcommac** [comment]
The one on master, 7 days ago. Why?

**Comment by tanner0101** [comment]
How have you configured the server channel? There's a test case similar to what you've done here: https://github.com/vapor/websocket-kit/blob/master/Tests/WebSocketKitTests/NIOWebSocketClientTests.swift#L40-L64

That appears to be working, albeit for text opcode. Not sure why binary would be any different though.
