### ISSUE TITLE
swift nio HTTPDecoder fails

### ISSUE THREAD

**Issue by keniwhat** [vapor/websocket-kit#73]
When using vapor web socket-kit, my swift app crashes at line 341 in swift-nio/NIOHTTP1/HTTPDecoder with a nil optional.
Debugging the code, the 'swap' function did not work.
This is a Linux only issue. It works fine on MacOS.
Swift version 5.2.4 and 5.1.5 tested.
websocket-kit version 2.1.0 and master tested.

All combinations fail on Linux.

**Comment by tanner0101** [comment]
Hi @keniwhat, thanks for reporting. If the crash is happening in the `NIOHTTP1` module, you should report the bug to: https://github.com/apple/swift-nio/issues.
