### ISSUE TITLE
Close promise not completed

### ISSUE THREAD

**Issue by tanner0101** [vapor/websocket-kit#76]
In some situations the promise passed to `WebSocket.close` is not being completed.

**Comment by lmcd** [comment]
I'm seeing the process stall when I `wait` on the `close` promise

**Comment by tanner0101** [comment]
This is potentially related to https://github.com/vapor/vapor/issues/2451. Working on tracking it down.

**Comment by tanner0101** [comment]
In case this _is_ related to the previous issue, https://github.com/vapor/vapor/pull/2472 will fix it. @lmcd could you give that a try? Assuming you are using Vapor + WebSockets here.
