### ISSUE TITLE
Upgrade swift-nio-ssl to 2.10.2

### ISSUE THREAD

**Issue by xanderdunn** [vapor/websocket-kit#83]
websocket-kit is currently pegged to swift-nio-ssl 2.0.0. Could you please update this to 2.10.2, which includes a fix that allows swift-nio-ssl to build with Swift For TensorFlow and latest Swift trunk. See apple/swift-nio-ssl#259.

Currently websocket-kit fails to build on Swift For TensorFlow and latest Swift trunk as a result of its swift-nio-ssl dependency version.

Thanks!

**Comment by 0xTim** [comment]
@xanderdunn it should still be possible to build because SwiftPM should take the latest possible version right?

**Comment by xanderdunn** [comment]
Oh right, the `from` parameter in Package.swift just begs a lower bound on the version, not an exact version. It does indeed build after `swift package update` brings swift-nio-ssl up to date. Thanks!

**Comment by 0xTim** [comment]
Yeah `from` is short hand for `upToNextMajor`
